config:
  port: 8081
  service_name: YourService
  service_address: 127.0.0.1:50051

urlmapping:
  - GET /hello SayHello
  - GET /eat_apple/{num:[0-9]+} EatApple
  - GET /a/a EatApple
  - POST /a/a SayHello
  - GET /a/b EatApple
  - GET /a/c EatApple
